version: '3.8'

services:
  db:
    image: postgres:15
    container_name: messaging_db_container
    restart: always
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: password_dev
      POSTGRES_DB: messaging_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: